version: '2'
# Create networks to be used to isolate containers
networks:
  # Server network to hold database and backend
  server_network:
    driver: bridge

# Define services to be run.
services:
  database:
    build: ./database
    networks:
      # Add the database service to the servernetwork.
      - server_network
  application:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - ./application:/application/code
    env_file:
      # Get the configuration from the dotenv file.
      - ./application/.env
    ports:
      - "3000"
    links:
      - database
    networks:
      - server_network
    depends_on:
      - database
    restart: always

  webserver:
      build: ./server
      restart: always
      volumes:
        - "/etc/letsencrypt"
      links:
          - application
      ports:
          - "8080:80"
          - "443:443"
      networks:
        - server_network
      depends_on:
        - application
